# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='isPolice',
            field=models.IntegerField(),
        ),
    ]
