# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('police', '0002_auto_20160410_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('isCriminal', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('job', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='police',
            name='post',
            field=models.CharField(max_length=30),
        ),
    ]
