# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_auto_20160412_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='gender',
            field=models.TextField(default='Male'),
        ),
    ]
