# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('police', '0006_auto_20160415_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal_Record',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('jail', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('section', models.TextField()),
                ('fine', models.IntegerField(default=0)),
            ],
        ),
    ]
